Repository tompais/Mobius-API, pull requests merged in 2020-11, with the labels that each got.

#71 [FTR] Memory and Visualization exercises processed
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/BooleanGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/TextGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/BooleanTestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TextTestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/resources/data.sql
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/PatientServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/TestConstants.kt
Labels: feature

#78 [ENH] Added image for visualization
  .gitignore
  src/main/resources/data.sql
  src/main/resources/static/audios/Bicicleta-Cuchara-Manzana.mp3
  src/main/resources/static/images/Tigre.png
Labels: enhancement

#82 [FIX] Imgbot
  .github/workflows/branch-name.yml
Labels: fix

#84 [FIX] User Without Guardian
  src/main/resources/data.sql
Labels: fix

#85 [ENH] ImgBot Label
  .github/pr-labeler.yml
Labels: enhancement

#88 [FTR] [ALF-99] Repetition Test Game
  src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TestGameAnswersRequest.kt
  src/main/resources/data.sql
  src/main/resources/static/audios/Flan-Frutilla-Frambuesas.mp3
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: feature

#89 [FTR] Result of comprehension exercise processed
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/ComprehensionGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/resources/data.sql
  src/main/resources/static/audios/Triangulo-Cuadrado-Circulo.mp3
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: feature

#92 [FTR] [ALF-101] Reading Test Game
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/NumericGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/NumericTestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/resources/data.sql
  src/main/resources/static/images/lectura-1.png
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: feature

#93 [FTR] Result of writing exercise processed
  src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/resources/data.sql
  src/main/resources/static/texts/LluviaTejado.txt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: feature

#96 [HOTFIX] Last Game Category
  .github/workflows/auto-approve.yml
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/GameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IGameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IGameRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/GameService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IGameService.kt
  src/main/resources/data.sql
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/GameServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/PatientServiceTest.kt
Labels: hotfix

#100 [HOTFIX] Auto approve
  .github/workflows/auto-approve.yml
Labels: hotfix

#102 [HOTFIX] Orientation questions and text file for writing exercise refactored
  src/main/resources/data.sql
  src/main/resources/static/texts/LluviaTejado.txt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: hotfix

#104 [FTR] Autosquash
  .github/pr-labeler.yml
  .github/workflows/auto-approve.yml
  .github/workflows/autosquash.yml
Labels: feature

#107 [RFT] Tasks
  src/main/kotlin/com/coder_rangers/mobius_api/models/Answer.kt
  src/main/resources/data.sql
  src/main/resources/static/images/Tigre.png
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: refactor

#109 [FTR] [ALF-102] Image Upload
  .gitignore
  build.gradle.kts
  src/main/kotlin/com/coder_rangers/mobius_api/config/AmazonS3ClientConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/ImageController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/PatientController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/IllegalImageExtensionException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/responses/UploadImageResponse.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/AmazonS3Service.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/ImageService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IAmazonS3Service.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IImageService.kt
  src/main/resources/application.properties
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/BaseIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/ImageIntegrationTest.kt
  src/test/resources/application.properties
  src/test/resources/images/spiderman.jpg
  src/test/resources/images/spiderman.png
Labels: feature

#110 [FTR] Endpoint to get test result
  codecov.yml
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/PatientController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/TaskResultDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/ITaskResultDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/ITaskResultRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/enums/DementiaLevel.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/TestNotFinishedException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
  src/main/kotlin/com/coder_rangers/mobius_api/responses/PatientTestResult.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/TaskResultService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IMentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IPatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/ITaskResultService.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/TaskResultServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/TestConstants.kt
Labels: feature

#113 [ENH] Dependencies
  build.gradle.kts
Labels: enhancement

#114 [FTR] Endpoint to clean the patient test progress
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/InternalController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Patient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/TaskResultService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IPatientService.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/InternalIntegrationTest.kt
Labels: feature

#117 [RFT] Image Upload
  build.gradle.kts
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/ImageController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/ImageService.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/ImageIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/TaskResultServiceTest.kt
  src/test/resources/images/spiderman-2.JPG
  src/test/resources/images/spiderman-2.PNG
Labels: refactor

#118 [HOTFIX] CORS
  src/main/kotlin/com/coder_rangers/mobius_api/config/GlobalRepositoryRestConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/config/WebConfig.kt
Labels: hotfix

#121 [FTR] Drawing exercise result processed
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/AttentionGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/ComprehensionGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/ImageGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/TaskDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/ITaskDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/ITaskRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/FinishedTestException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/IncompatibleImageDimensionsException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/TaskNotFoundException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/ImagePatientAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Input.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/AmazonS3Service.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/TaskService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IAmazonS3Service.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/ITaskService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/utils/ImageUtils.kt
  src/main/resources/data.sql
  src/main/resources/static/images/Casa.png
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/PatientServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/TaskServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/MockUtils.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/TestConstants.kt
  src/test/resources/images/Casa.png
  src/test/resources/images/dibujo-chico.png
  src/test/resources/images/dibujo.png
Labels: feature

#125 [RFT] Inputs types refactored
  .github/pr-labeler.yml
  src/main/kotlin/com/coder_rangers/mobius_api/models/Input.kt
  src/main/resources/data.sql
Labels: refactor

#128 Changed \n by <br/>
  src/main/resources/data.sql
Labels: refactor

#131 [HOTFIX] Slash removed
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/ImageGameAnswersResolver.kt
Labels: hotfix

#133 [HOTFIX] General Fixes
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/ImageGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/PatientAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
  src/main/resources/data.sql
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/resources/images/dibujo-menos70.png
Labels: hotfix

#135 [HOTFIX] Dementia Level Score
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/TaskResultService.kt
  src/main/resources/data.sql
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/TaskResultServiceTest.kt
Labels: hotfix

#137 [ENH] [ALF-114] Upload Image and Drawing Resolver
  build.gradle.kts
  codecov.yml
  src/main/kotlin/com/coder_rangers/mobius_api/MobiusApiApplication.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/DrawingGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/ImageController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/IncompatibleImageDimensionsException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/ChannelTopicConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/MessageListenerConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/RedisConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/messages/UploadFileMessage.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/publishers/UploadFileToS3Publisher.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/suscribers/RedisMessageSubscriber.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/suscribers/UploadFileToS3Subscriber.kt
  src/main/kotlin/com/coder_rangers/mobius_api/responses/SaveImageResponse.kt
  src/main/kotlin/com/coder_rangers/mobius_api/responses/UploadImageResponse.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/AmazonS3Service.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/ImageService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IAmazonS3Service.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IImageService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/utils/ImageUtils.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/BaseIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/ImageIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/SecurityIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/MockUtils.kt
  src/test/resources/images/spiderman-2.JPG
  src/test/resources/images/spiderman-2.PNG
Labels: enhancement
