Repository tompais/Mobius-API, pull requests merged in 2020-12, with the labels that each got.

#138 [ENH] [ALF-115] Patient Registration
  build.gradle.kts
  src/main/kotlin/com/coder_rangers/mobius_api/config/LocaleResolverConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/GuardianDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/PatientDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IGuardianDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IPatientDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IGuardianRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IPatientRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/ConflictException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/DuplicatedPatientException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/PatientIsAGuardianException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/mail/clients/implementations/EmailClient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/mail/clients/interfaces/IEmailClient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/mail/services/implementations/EmailService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/mail/services/interfaces/IEmailService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Guardian.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Patient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/User.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/ChannelTopicConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/MessageListenerConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/RedisConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/publishers/UserRegisteredPublisher.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/suscribers/RedisMessageSubscriber.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/suscribers/UploadFileToS3Subscriber.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/suscribers/UserRegisteredSubscriber.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/SignInRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/SignUpRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/GuardianService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/SecurityService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IGuardianService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IPatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/utils/PasswordUtils.kt
  src/main/kotlin/com/coder_rangers/mobius_api/validators/annotations/ValidPassword.kt
  src/main/kotlin/com/coder_rangers/mobius_api/validators/classes/ValidPasswordValidator.kt
  src/main/resources/data.sql
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/BaseIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/InternalIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/SecurityIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/dao/PatientDAOTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/PatientServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/SecurityServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/TaskResultServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/MockUtils.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/TestConstant.kt
Labels: enhancement

#144 [FTR] Possible Answers
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/AttentionGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/ComprehensionGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/DrawingGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/NumericGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/TextGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/TextGameAnswersWithResultsResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/interfaces/IGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/TaskResultDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/ITaskResultDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Answer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/CharAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/CharPatientAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/ImageAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/ImagePatientAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Input.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/NumericAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/NumericPatientAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/PatientAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/TextPatientAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/TaskResultService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/TaskService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/ITaskResultService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/ITaskService.kt
  src/main/resources/data.sql
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/TaskServiceTest.kt
Labels: feature

#143 [FTR] Endpoint to get list of game categories and recommended category
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/PatientController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/GameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/TaskDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/TaskResultDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IGameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/ITaskDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/ITaskResultDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IGameRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/ITaskResultRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/GameService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/TaskResultService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IGameService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IPatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/ITaskResultService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/view/models/HomeViewModel.kt
  src/main/resources/data.sql
  src/main/resources/static/audios/Casa-Mesa-Pato.mp3
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/PatientServiceTest.kt
Labels: feature

#150 [HOTFIX] Possible answers fixed
  src/main/resources/data.sql
Labels: hotfix

#152 [RFT] Endpoints to get and process games refactored
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/PatientController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/GameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IGameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IGameRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/ExclusiveTestCategoryException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/TestNotFinishedException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/AttentionGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/AttentionTestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/GameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/NumericGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TextGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TextGameAnswersWithResultsRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/GameService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IGameService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IMentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IPatientService.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/GameServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/PatientServiceTest.kt
Labels: refactor

#156 [FTR] Added test status into singin dto
  src/main/kotlin/com/coder_rangers/mobius_api/responses/SignInResponse.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/SecurityService.kt
Labels: refactor

#159 [HOTFIX] Guardian and Patient Relationship
  src/main/kotlin/com/coder_rangers/mobius_api/models/Guardian.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Patient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/SecurityService.kt
Labels: hotfix

#161 [FTR] Endpoint to send a weekly report of the patients
  build.gradle.kts
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/ScheduleController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/PatientDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IPatientDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IPatientRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dto/WeeklyReportDTO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/emails/services/implementations/EmailService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/emails/services/interfaces/IEmailService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Patient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/ChartRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/ScheduleService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/TaskResultService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IPatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IScheduleService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/utils/MailConstant.kt
  src/main/kotlin/com/coder_rangers/mobius_api/utils/TaskResultUtils.kt
  src/main/resources/email/templates/patient-test-results.html
  src/main/resources/email/templates/weekly-report.html
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/ScheduleIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/MockUtils.kt
Labels: feature

#164 [ENH] Test Results
  src/main/kotlin/com/coder_rangers/mobius_api/MobiusApiApplication.kt
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/ScheduleController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/enums/DementiaLevel.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/ScheduleService.kt
  src/main/resources/email/templates/patient-test-results.html
Labels: enhancement

#167 [ENH] More games added and test score changed
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/resources/data.sql
  src/main/resources/email/templates/patient-test-results.html
  src/main/resources/static/images/Gorila.jpg
  src/main/resources/static/images/lectura-2.png
  src/main/resources/static/texts/InviernoCasas.txt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/MockUtils.kt
Labels: enhancement

#170 [ENH] Image Comparison
  build.gradle.kts
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/DrawingGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/config/ObjectMapperConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/config/WebClientConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/IncompatibleImageDimensionsException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/responses/imagga/CompareResponse.kt
  src/main/kotlin/com/coder_rangers/mobius_api/responses/imagga/UploadResponse.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/ImageService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IImageService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/utils/ImageUtils.kt
  src/main/resources/application.properties
  src/main/resources/static/images/Casa.png
  src/test/kotlin/com/coder_rangers/mobius_api/config/WebTestClientConfig.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/BaseIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/resources/application.properties
  src/test/resources/images/Casa.png
  src/test/resources/images/dibujo-chico.png
  src/test/resources/images/dibujo-menos70.png
  src/test/resources/images/spiderman.png
Labels: enhancement

#171 [FIX] Imagga Rate Limit
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/ImageService.kt
Labels: fix

#149 [FTR] [ALF-117] Spring Security JWT
  build.gradle.kts
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/JWTGenerator.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/interfaces/IJWTGenerator.kt
  src/main/kotlin/com/coder_rangers/mobius_api/config/OpenAPIConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/config/SecurityConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/PatientController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IGameRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IGuardianRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IPatientRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/ITaskRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/ITaskResultRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/filters/JWTAuthorizationFilter.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/JedisConnectionConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/RedisConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/responses/SignInResponse.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/SecurityService.kt
  src/main/resources/application.properties
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/BaseIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/SecurityServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/TestConstant.kt
  src/test/resources/application.properties
Labels: feature

#176 [ENH] More games added
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/GameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IGameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IGameRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/GameService.kt
  src/main/resources/data.sql
  src/main/resources/static/images/Lobo.jpg
  src/main/resources/static/images/lectura-3.png
  src/main/resources/static/texts/VeranoPlaya.txt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/GameServiceTest.kt
Labels: enhancement

#177 [ENH] Game Variations
  src/main/resources/data.sql
  src/main/resources/static/audios/Atún-Naranja-Adorno.mp3
  src/main/resources/static/audios/Burrito-Barrigón-Resbalón.mp3
  src/main/resources/static/audios/Carbón-Ventilador-Pájaro.mp3
  src/main/resources/static/audios/Cojines-Reina-Gemas-Sultán.mp3
  src/main/resources/static/audios/Computadora-Monitor-Ratón.mp3
  src/main/resources/static/audios/Corona-Cerveza-Caja.mp3
  src/main/resources/static/audios/Libro-Vaso-Cuaderno.mp3
  src/main/resources/static/audios/Pelota-Raqueta-Árbitro.mp3
  src/main/resources/static/audios/Pepe-Pela-Patatas.mp3
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: enhancement

#182 [ENH] More drawing games added
  src/main/resources/data.sql
  src/main/resources/static/images/Celular.png
  src/main/resources/static/images/Pino.png
Labels: enhancement

#188 [FIX] General Issues
  src/main/kotlin/com/coder_rangers/mobius_api/MobiusApiApplication.kt
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/ScheduleController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/ImageService.kt
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/email/templates/patient-test-results.html
Labels: fix
