Repository tompais/Mobius-API, pull requests merged in 2020-10, with the labels that each got.

#2 [FTR] Global Handler Exception
  build.gradle.kts
  codecov.yml
  src/main/kotlin/com/coder_rangers/mobius_api/config/Slf4jMDCFilterConfiguration.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/APIException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/BadRequestException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/InternalServerErrorException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/handler/RestResponseEntityExceptionHandler.kt
  src/main/kotlin/com/coder_rangers/mobius_api/filters/Slf4jMDCFilter.kt
  src/main/resources/logback-spring.xml
Labels: feature

#3 [FTR] Object Mapper Configuration
  build.gradle.kts
  src/main/kotlin/com/coder_rangers/mobius_api/config/ObjectMapperConfig.kt
Labels: feature

#4 [FTR] Open-API
  build.gradle.kts
Labels: feature

#8 [FTR] Slack Release Notification
  .github/workflows/create-release-pull-request.yml
Labels: feature

#11 [FTR] [ALF-66] User Registration
  build.gradle.kts
  src/main/kotlin/com/coder_rangers/mobius_api/config/ObjectMapperConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/SecurityController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/APIException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/SignUpRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/SecurityService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/ISecurityService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/validators/annotations/DifferentPersonalAndGuardianEmail.kt
  src/main/kotlin/com/coder_rangers/mobius_api/validators/annotations/OverEighteen.kt
  src/main/kotlin/com/coder_rangers/mobius_api/validators/classes/DifferentPersonalAndGuardianEmailValidator.kt
  src/main/kotlin/com/coder_rangers/mobius_api/validators/classes/OverEighteenValidator.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/BaseIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/SecurityIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/MockUtils.kt
Labels: feature

#14 [FTR] [ALF-69] User Sign In
  build.gradle.kts
  src/main/kotlin/com/coder_rangers/mobius_api/MobiusApiApplication.kt
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/SecurityController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/PatientDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IPatientDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IPatientRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/enums/Genre.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/NotFoundException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/PatientNotFoundException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/handler/RestResponseEntityExceptionHandler.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Guardian.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Patient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/User.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/SignInRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/SignUpRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/SecurityService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/ISecurityService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/validators/classes/DifferentPersonalAndGuardianEmailValidator.kt
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/SecurityIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/SecurityServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/MockUtils.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/TestConstants.kt
Labels: feature

#18 [FTR] Funny Commments
  .github/workflows/funny-comment.yml
Labels: feature

#19 [FTR] Sign In Response
  build.gradle.kts
  src/main/kotlin/com/coder_rangers/mobius_api/config/WebConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/SecurityController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/handler/RestResponseEntityExceptionHandler.kt
  src/main/kotlin/com/coder_rangers/mobius_api/responses/SignInResponse.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/SecurityService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/ISecurityService.kt
Labels: feature

#15 Feature/create models
  src/main/kotlin/com/coder_rangers/mobius_api/models/Answer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Category.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
Labels: feature

#22 [RFT] Global Handler Exception
  src/main/kotlin/com/coder_rangers/mobius_api/error/handler/RestResponseEntityExceptionHandler.kt
Labels: refactor

#30 [HOTFIX] Swagger UI
  src/main/kotlin/com/coder_rangers/mobius_api/config/WebConfig.kt
Labels: hotfix

#32 [HOTFIX] Many to Many Relations
  src/main/kotlin/com/coder_rangers/mobius_api/models/Guardian.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
Labels: hotfix

#28 [FTR] [ALF-72] Registration Confirmation Email
  src/main/kotlin/com/coder_rangers/mobius_api/mail/clients/implementations/EmailClient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/mail/clients/interfaces/IEmailClient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/mail/services/implementations/EmailService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/mail/services/interfaces/IEmailService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Answer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/SecurityService.kt
  src/main/resources/application.properties
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/SecurityIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/SecurityServiceTest.kt
  src/test/resources/application.properties
Labels: feature

#29 [ENH] Redis
  build.gradle.kts
  codecov.yml
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/ChannelTopicConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/JedisConnectionConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/MessageListenerConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/RedisConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/config/RedisSerializerConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/publishers/MessagePublisher.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/publishers/RedisMessagePublisher.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/publishers/UserRegisteredPublisher.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/suscribers/RedisMessageSubscriber.kt
  src/main/kotlin/com/coder_rangers/mobius_api/notifications/redis/suscribers/UserRegisteredSubscriber.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/SecurityService.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/SecurityIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/controllers/PingControllerTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/SecurityServiceTest.kt
Labels: enhancement

#36 [FTR] Get Mental Test Game
  codecov.yml
  src/main/kotlin/com/coder_rangers/mobius_api/config/WebConfig.kt
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/PatientController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/converters/CategoryTypeConverter.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/GameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/PatientDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IGameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IPatientDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IGameRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IPatientRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/ITestProgressRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/BadRequestException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/FinishedTestException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/GameNotFoundException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/NotFoundException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/PatientNotFoundException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/handler/RestResponseEntityExceptionHandler.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Category.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Input.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Patient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Resource.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/GameService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IGameService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IMentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IPatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/validators/annotations/ValidTestCategoryType.kt
  src/main/kotlin/com/coder_rangers/mobius_api/validators/classes/ValidTestCategoryTypeValidator.kt
  src/main/resources/data.sql
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/BaseIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/SecurityIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/GameServiceTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/MockUtils.kt
  src/test/kotlin/com/coder_rangers/mobius_api/utils/TestConstants.kt
Labels: feature

#37 [RFT] Sign In
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/SecurityController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/responses/SignInResponse.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/SecurityService.kt
  src/main/resources/data.sql
Labels: refactor

#43 [FTR] Base process answers
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/PatientController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/PatientDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IPatientDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Patient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/TestProgress.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/TaskAnswer.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/FixationTaskAnswerRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/GameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/OrientationTaskAnswerRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IPatientService.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: feature

#46 [RFT] Base Process Answers
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/PatientController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/FixationTestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/OrientationTestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IPatientService.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/PatientServiceTest.kt
Labels: refactor

#48 [FTR] [ALF-86] Fixation Test
  build.gradle.kts
  codecov.yml
  src/main/kotlin/com/coder_rangers/mobius_api/controllers/PatientController.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/TaskResultDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/ITaskResultDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/ITaskResultRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/ForbiddenException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/NotAllTasksProvidedException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/TestCategoryAlreadyPlayedException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/PatientTaskAnswers.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/FixationTestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/OrientationTestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/BaseGameAnswersResolverService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/FixationGameAnswersResolverService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/GameService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/TaskResultService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IGameAnswersResolverService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IGameService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IMentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IPatientService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/ITaskResultService.kt
  src/main/resources/data.sql
  src/main/resources/static/Bicicleta-Cuchara-Manzana.mp3
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/PatientServiceTest.kt
Labels: feature

#51 [RFT] Test Progress
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/ITestProgressRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/enums/TestStatus.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/ForbiddenException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/error/exceptions/TestCategoryAlreadyPlayedException.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Patient.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/TestProgress.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/PatientService.kt
  src/main/resources/data.sql
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/dao/PatientDAOTest.kt
  src/test/kotlin/com/coder_rangers/mobius_api/unit/services/PatientServiceTest.kt
Labels: refactor

#52 [FTR] Answers of orientation game processed
  build.gradle.kts
  codecov.yml
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/BaseGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/FixationGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/OrientationGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/interfaces/IGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: feature

#47 [ENH] Get mental test game improved
  src/main/kotlin/com/coder_rangers/mobius_api/dao/implementations/GameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/dao/interfaces/IGameDAO.kt
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/IGameRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Task.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/GameService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/interfaces/IGameService.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: enhancement

#56 [FTR] [ALF-88] Get Calculation Game
  src/main/kotlin/com/coder_rangers/mobius_api/models/Game.kt
  src/main/resources/data.sql
Labels: feature

#57 [FTR] Calculation game answers processed
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/CalculationGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/CalculationTestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/requests/categories/TestGameAnswersRequest.kt
  src/main/kotlin/com/coder_rangers/mobius_api/services/implementations/MentalTestService.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: feature

#60 [HOTFIX] Fixation and Calculation Answer Resolvers
  codecov.yml
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/CalculationGameAnswersResolver.kt
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/FixationGameAnswersResolver.kt
  src/test/kotlin/com/coder_rangers/mobius_api/integrations/PatientIntegrationTest.kt
Labels: hotfix

#62 [HOTFIX] Sort Numeric Answers
  codecov.yml
  src/main/kotlin/com/coder_rangers/mobius_api/components/implementations/CalculationGameAnswersResolver.kt
Labels: hotfix

#64 [FTR] Subscribers
  src/main/kotlin/com/coder_rangers/mobius_api/database/repositories/ISubscriberRepository.kt
  src/main/kotlin/com/coder_rangers/mobius_api/models/Subscriber.kt
Labels: feature

#67 [FIX] Data Rest CORS
  src/main/kotlin/com/coder_rangers/mobius_api/config/GlobalRepositoryRestConfig.kt
Labels: fix
